### ISSUE TITLE
Provide ORCID iD for all contributors

### ISSUE THREAD

**Issue by larnsce** [openwashdata/chckapmalawi#1]
Hi @Kumpukwe, could you please share email address and ORCID iD of all contributors to this dataset?

- first name
- surname
- ORCID id
- email address

**Comment by Kumpukwe** [comment]
Rhodrick Sagawa  (0009-0004-7294-4120) rhodrick@baseflowmw.org
Paul Kumpukwe (0009-0002-8797-8046) paul@baseflowmw.org
Veronica Chinangwa (0009-0005-7549-9584) veronica@baseflowmw.org
Baleke Banda (0009-0005-7582-1238) baleke@baseflowmw.org
Rodney Kananji (0009-0005-5277-9778) rodney@baseflowmw.org
Feston Bwanyula (0009-0000-6731-5048) feston@baseflowmw.org
Gloria Maliana (0009-0003-0563-3579) malianagloria24@gmail.com
Given Ngwira (0009-0002-7847-4057) given@baseflowmw.org
